#!/usr/bin/env bash
    # Example on Cityscapes
     python -m torch.distributed.launch --nproc_per_node=2 train.py \
        --dataset cityscapes \
        --arch network.deepv3.DeepMobileNetV3PlusD_HANet \
        --city_mode 'train' \
        --lr_schedule poly \
        --lr 0.000001 \
        --poly_exp 0.9 \
        --hanet_lr 0.000001 \
        --hanet_poly_exp 0.9 \
        --max_cu_epoch 10000 \
        --class_uniform_pct 0.7 \
        --class_uniform_tile 1024 \
        --syncbn \
        --sgd \
        --crop_size 768 \
        --scale_min 0.5 \
        --scale_max 2.0 \
        --rrotate 0 \
        --color_aug 0.25 \
        --gblur \
        --max_iter 2000 \
        --bs_mult 6 \
        --hanet 0 0 0 2 0 \
        --hanet_set 3 16 3 \
        --hanet_pos 2 1 \
        --pos_rfactor 8 \
        --dropout 0.12 \
        --pos_noise 0.3 \
        --aux_loss \
        --date 0101 \
        --exp m_os16_hanet \
        --ckpt ./logs/ \
        --tb_path ./logs/ 
